### ISSUE TITLE
Unable to build on 

### ISSUE THREAD

**Issue by mholo65** [gep13/chocolatey-vscode#82]
## Expected Behavior
It should build 😄 

## Current Behavior
Running `.\build.ps1` will result in following output:
```
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Error: The assembly 'MagicChunks.Cake, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.23.0).
This assembly must reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```

Running
```
$Env:CAKE_SETTINGS_SKIPVERIFICATION="true"
.\build.ps1
```
Will result in following log:
```
========================================
Package-Extension
========================================
Executing task: Package-Extension
Executing prepublish script 'npm run vscode:prepublish'...
Error: Command failed: npm run vscode:prepublish
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! chocolatey-vscode@0.2.2 compile: `%APPDATA%/npm/tsc -p ./`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the chocolatey-vscode@0.2.2 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mb\AppData\Roaming\npm-cache\_logs\2019-02-08T07_44_00_306Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! chocolatey-vscode@0.2.2 vscode:prepublish: `npm run compile`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the chocolatey-vscode@0.2.2 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mb\AppData\Roaming\npm-cache\_logs\2019-02-08T07_44_00_325Z-debug.log

An error occurred when executing task 'Package-Extension'.
```

Examining log ` C:\Users\mb\AppData\Roaming\npm-cache\_logs\2019-02-08T07_44_00_325Z-debug.log` shows following:

```
9 verbose lifecycle chocolatey-vscode@0.2.2~vscode:prepublish: CWD: C:\Users\mb\src\gh\chocolatey-vscode
10 silly lifecycle chocolatey-vscode@0.2.2~vscode:prepublish: Args: [ '/d /s /c', 'npm run compile' ]
11 silly lifecycle chocolatey-vscode@0.2.2~vscode:prepublish: Returned: code: 2  signal: null
12 info lifecycle chocolatey-vscode@0.2.2~vscode:prepublish: Failed to exec vscode:prepublish script
13 verbose stack Error: chocolatey-vscode@0.2.2 vscode:prepublish: `npm run compile`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid chocolatey-vscode@0.2.2
15 verbose cwd C:\Users\mb\src\gh\chocolatey-vscode
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "vscode:prepublish"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error chocolatey-vscode@0.2.2 vscode:prepublish: `npm run compile`
22 error Exit status 2
23 error Failed at the chocolatey-vscode@0.2.2 vscode:prepublish script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

## Possible Solution
Dunno, too old node/npm version? Update of deps breaking?

## Steps to Reproduce (for bugs)
1. Remove `node_modules`
2. Execute `.\build.ps1`

## Context
I'm trying to build this, also unable to start debugging from VS Code as I am unable to compile (both from build script and inside VS Code)

## Your Environment
* Module version used: latest from `develop` branch.
* Operating System and PowerShell version: Windows 10 (PSVersion : 5.1.17763.134)

**Comment by gep13** [comment]
@mholo65 can you run the following?

` tsc --version`
`npm --version`
`node --version`
`& where.exe tsc`

and compare your output to the following:

![image](https://user-images.githubusercontent.com/1271146/52475081-48510680-2b92-11e9-826b-9d4567004bef.png)

As it works on my machine 😄

**Comment by mholo65** [comment]
```
> tsc --version
Version 2.9.2
> npm --version
5.6.0
> node --version
v8.11.3
> & where.exe tsc
C:\Users\mb\AppData\Roaming\npm\tsc
C:\Users\mb\AppData\Roaming\npm\tsc.cmd
```

**Comment by mholo65** [comment]
closing, nvm now it works... I had some deps modified, therefore it didn't compile...

**Comment by gep13** [comment]
@mholo65 ok, cool, thanks for following up!
